appname:    "JsonLinux"
charset:    "UTF-8"
serializer: "JSON"

engines:
    JSON:
        pretty:          1
        allow_blessed:   0
        canonical:       1
        convert_blessed: 0
        utf8:            1

