appname:    "JsonLinux"
charset:    "UTF-8"
serializer: "JSON"

engines:
    JSON:
        pretty:          0
        allow_blessed:   0
        canonical:       0
        convert_blessed: 0
        utf8:            0

